name: kide
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add these lines
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1 # Use a recent version

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true # Enable generation for intl

  assets:
    - assets/images/
